// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StardewValleyAPI.API.DbContexts;

namespace StardewValleyAPI.Migrations
{
    [DbContext(typeof(StardewValleyLibraryContext))]
    partial class StardewValleyLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StardewValleyAPI.API.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriticalStrikeChance")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("Stats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba01"),
                            CriticalStrikeChance = ".02",
                            Damage = "2-5",
                            Description = "A rusty, dull old Sword.",
                            Image = "/images/Rusty_Sword.png",
                            Level = 1,
                            Location = "The Mines entrance",
                            Name = "Rusty Sword",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba02"),
                            CriticalStrikeChance = ".02",
                            Damage = "3-7",
                            Description = "Not bad for a piece of carved wood.",
                            Image = "/images/Wooden_Blade.png",
                            Level = 2,
                            Location = "Adventurer s Guild",
                            Name = "Wooden Blade",
                            PurchasePrice = 250,
                            SellPrice = 100,
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba03"),
                            CriticalStrikeChance = ".02",
                            Damage = "4-8",
                            Description = "A standard metal blade.",
                            Image = "/images/Steel_Smallsword.png",
                            Level = 2,
                            Location = "The Mines floor 20 chest reward",
                            Name = "Steel SmallSword",
                            PurchasePrice = 0,
                            SellPrice = 100,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba04"),
                            CriticalStrikeChance = ".02",
                            Damage = "8-15",
                            Description = "Plated with silver to deter rust.",
                            Image = "/images/Silver_Saber.png",
                            Level = 3,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 20)",
                            Name = "Silver Saber",
                            PurchasePrice = 750,
                            SellPrice = 150,
                            Stats = "Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba05"),
                            CriticalStrikeChance = ".02",
                            Damage = "8-14",
                            Description = "It looks like a pirate owned this once.",
                            Image = "/images/Pirate%27s_Sword.png",
                            Level = 4,
                            Location = "The Mines (Floors 20+)",
                            Name = "Pirate s Sword",
                            PurchasePrice = 850,
                            SellPrice = 200,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba06"),
                            CriticalStrikeChance = ".02",
                            Damage = "9-17",
                            Description = "A finely crafted blade.",
                            Image = "/images/Cutlass.png",
                            Level = 4,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 25)",
                            Name = "Cutlass",
                            PurchasePrice = 1500,
                            SellPrice = 200,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba07"),
                            CriticalStrikeChance = ".02",
                            Damage = "12-25",
                            Description = "A heavy broadsword..",
                            Image = "/images/Iron_Edge.png",
                            Level = 4,
                            Location = "The Mines (Floors 40+)",
                            Name = "Iron Edge",
                            PurchasePrice = 0,
                            SellPrice = 200,
                            Stats = " Speed (−2), Defense (+1), Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba08"),
                            CriticalStrikeChance = ".02",
                            Damage = "8-18",
                            Description = "Made powerful by forest magic.",
                            Image = "/images/Forest_Sword.png",
                            Level = 5,
                            Location = "The Mines (Floors 20-60)",
                            Name = "Forest Sword",
                            PurchasePrice = 0,
                            SellPrice = 250,
                            Stats = " Speed (+2), Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba09"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-24",
                            Description = "It feels hopeful to wield.",
                            Image = "/images/Holy_Blade.png",
                            Level = 5,
                            Location = "The Mines (Floors 60+)",
                            Name = "Holy Blade",
                            PurchasePrice = 0,
                            SellPrice = 250,
                            Stats = " Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba10"),
                            CriticalStrikeChance = ".04",
                            Damage = "10-20",
                            Description = "Not very pleasant to wield.",
                            Image = "/images/Insect_Head.png",
                            Level = 6,
                            Location = "Bug drop",
                            Name = "Insect Head",
                            PurchasePrice = 10000,
                            SellPrice = 300,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba11"),
                            CriticalStrikeChance = ".02",
                            Damage = "20-32",
                            Description = "It s really heavy.",
                            Image = "/images/Claymore.png",
                            Level = 6,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 45)",
                            Name = "Claymore",
                            PurchasePrice = 2000,
                            SellPrice = 300,
                            Stats = " Speed (−4), Defense (+2, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba12"),
                            CriticalStrikeChance = "0",
                            Damage = "22-29",
                            Description = "It once belonged to an honorable knight.",
                            Image = "/images/Templar%27s_Blade.png",
                            Level = 6,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 55)",
                            Name = "Templar s Blade",
                            PurchasePrice = 4000,
                            SellPrice = 300,
                            Stats = "Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba13"),
                            CriticalStrikeChance = ".05",
                            Damage = "30-45",
                            Description = "It s glowing with vampire energy.",
                            Image = "/images/Dark_Sword.png",
                            Level = 8,
                            Location = "Haunted Skull drop",
                            Name = "Dark Sword",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = " Speed (-5, Weight (+5) ≈.08 chance of increasing Health, if it is below max.",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba14"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-35",
                            Description = "An heirloom from beyond the Gem Sea.",
                            Image = "/images/Neptune%27s_Glaive.png",
                            Level = 7,
                            Location = "Fishing Treasure Chests (Fishing Level 2+)",
                            Name = "Neptune s Glaive",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (−1), Defense (+2, Weight (+4)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba15"),
                            CriticalStrikeChance = ".02",
                            Damage = "29-44",
                            Description = "It looks like it could withstand anything.",
                            Image = "/images/Tempered_Broadsword.png",
                            Level = 8,
                            Location = "Skull Cavern",
                            Name = "Tempered BroadSword",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = " Speed (−3), Defense (+3, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba16"),
                            CriticalStrikeChance = ".02",
                            Damage = "30-45",
                            Description = "It s incredibly sharp.",
                            Image = "/images/Obsidian_Edge.png",
                            Level = 9,
                            Location = "The Mines floor 90 chest reward",
                            Name = "Obsidian Edge",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = " Speed (−1), Crit. Power (+10)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba17"),
                            CriticalStrikeChance = ".02",
                            Damage = "20-30",
                            Description = "A very light piece of sharpened bone.",
                            Image = "/images/Bone_Sword.png",
                            Level = 10,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 75)",
                            Name = "Bone Sword",
                            PurchasePrice = 6000,
                            SellPrice = 500,
                            Stats = " Speed (+4, Weight (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba18"),
                            CriticalStrikeChance = ".02",
                            Damage = "28-46",
                            Description = "Light and powerful.",
                            Image = "/images/Steel_Falchion.png",
                            Level = 14,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 90)",
                            Name = "Steel Falchion",
                            PurchasePrice = 9000,
                            SellPrice = 700,
                            Stats = " Speed (+4), Crit. Power (+20)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba19"),
                            CriticalStrikeChance = ".015",
                            Damage = "55-64",
                            Description = "A powerful blade forged in a pool of churning lava.",
                            Image = "/images/Lava_Katana.png",
                            Level = 15,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 120)",
                            Name = "Lava Katana",
                            PurchasePrice = 25000,
                            SellPrice = 750,
                            Stats = "Defense (+3), Crit. Power (+25, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba20"),
                            CriticalStrikeChance = ".02",
                            Damage = "60-80",
                            Description = "It s unlike anything you ve ever seen.",
                            Image = "/images/Galaxy_Sword.png",
                            Level = 26,
                            Location = "The Desert (bring a Prismatic Shard to the Three Pillars)",
                            Name = "Galaxy Sword",
                            PurchasePrice = 50000,
                            SellPrice = 1300,
                            Stats = " Speed (+4)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba21"),
                            CriticalStrikeChance = ".04",
                            Damage = "1-3",
                            Description = "A small, light blade.",
                            Image = "/images/Carving_Knife.png",
                            Level = 2,
                            Location = "The Mines (Floors 1-20)",
                            Name = "Carving Knife",
                            PurchasePrice = 0,
                            SellPrice = 100,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba22"),
                            CriticalStrikeChance = ".03",
                            Damage = "2-4",
                            Description = "A common Dagger.",
                            Image = "/images/Iron_Dirk.png",
                            Level = 2,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 15)",
                            Name = "Iron Dirk",
                            PurchasePrice = 500,
                            SellPrice = 100,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba23"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-5",
                            Description = "A swift little blade.",
                            Image = "/images/Wind_Spire.png",
                            Level = 3,
                            Location = "The Mines (Floors 21-40)",
                            Name = "Wind Spire",
                            PurchasePrice = 0,
                            SellPrice = 150,
                            Stats = " Crit. Power (+10), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba24"),
                            CriticalStrikeChance = ".04",
                            Damage = "7-12",
                            Description = "A weapon of choice for the swift and silent.",
                            Image = "/images/Burglar%27s_Shank.png",
                            Level = 8,
                            Location = "Skull Cavern (Serpents and crates)",
                            Name = "Burglar s Shank",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = " Crit. Power (+25)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba25"),
                            CriticalStrikeChance = ".03",
                            Damage = "4-10",
                            Description = "The blade is made of purified quartz.",
                            Image = "/images/Crystal_Dagger.png",
                            Level = 9,
                            Location = "The Mines floor 60 chest reward",
                            Name = "Crystal Dagger",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = " Crit. Power (+50, Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba26"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-26",
                            Description = "It came from the sea, but it s still sharp.",
                            Image = "/images/Broken_Trident.png",
                            Level = 11,
                            Location = "Fishing treasure chests",
                            Name = "Broken Trident",
                            PurchasePrice = 0,
                            SellPrice = 550,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba27"),
                            CriticalStrikeChance = ".06",
                            Damage = "24-30",
                            Description = "The blade is made of an iridium alloy.",
                            Image = "/images/Wicked_Kris.png",
                            Level = 15,
                            Location = "Skull Cavern crates",
                            Name = "Wicked Kris",
                            PurchasePrice = 0,
                            SellPrice = 750,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba28"),
                            CriticalStrikeChance = ".02",
                            Damage = "30-40",
                            Description = "It s unlike anything you ve seen.",
                            Image = "/images/Galaxy_Dagger.png",
                            Level = 20,
                            Location = "Adventurer s Guild (after obtaining the Galaxy Sword)",
                            Name = "Galaxy Dagger",
                            PurchasePrice = 35000,
                            SellPrice = 1000,
                            Stats = " Speed (+1), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba29"),
                            CriticalStrikeChance = ".02",
                            Damage = "6-11",
                            Description = "An old, heavy bone caked in centuries of grime.",
                            Image = "/images/Femur.png",
                            Level = 1,
                            Location = "Found while digging outside the mines.",
                            Name = "Femur",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba30"),
                            CriticalStrikeChance = ".02",
                            Damage = "9-16",
                            Description = "A solid piece of wood, crudely chiseled into a Club shape.",
                            Image = "/images/Wood_Club.png",
                            Level = 2,
                            Location = "The Mines (Floors 1-39)",
                            Name = "Wood Club.",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba31"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-24",
                            Description = "The solid head packs a punch. Relatively light for a Club.",
                            Image = "/images/Wood_Mallet.png",
                            Level = 2,
                            Location = "The Mines (Floors 40+)",
                            Name = "Wood Mallet",
                            PurchasePrice = 2000,
                            SellPrice = 0,
                            Stats = " Speed (+2, Weight (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba32"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-27",
                            Description = "It s incredibly heavy.",
                            Image = "/images/Lead_Rod.png",
                            Level = 3,
                            Location = "The Mines (Floors 40+)",
                            Name = "Lead Rod",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (−4)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba33"),
                            CriticalStrikeChance = ".02",
                            Damage = "40-55",
                            Description = "An extremely heavy gavel that ll send foes flying.",
                            Image = "/images/The_Slammer.png",
                            Level = 5,
                            Location = "Skull Cavern (Floors 40+)",
                            Name = "The Slammer",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (−2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba34"),
                            CriticalStrikeChance = ".02",
                            Damage = "70-90",
                            Description = "It s made from an ultra-light material you ve never seen before.",
                            Image = "/images/Galaxy_Hammer.png",
                            Level = 9,
                            Location = "Adventurer s Guild (after obtaining the Galaxy Sword)",
                            Name = "Galaxy Hammer",
                            PurchasePrice = 75000,
                            SellPrice = 0,
                            Stats = " Speed (+2, Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba35"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "The sweet spot is dented from Alex s famous Grand Slam.",
                            Image = "/images/Alex%27s_Bat.png",
                            Level = 1,
                            Location = "Unobtainable",
                            Name = "Alex s Bat",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Stats = " Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba36"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "It s seen better days.",
                            Image = "/images/Sam%27s_Old_Guitar.png",
                            Level = 1,
                            Location = "Unobtainable",
                            Name = "Sam s Old Guitar",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Stats = " Speed (+1), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba37"),
                            CriticalStrikeChance = ".04",
                            Damage = "3-5",
                            Description = "Only the nimble hands of an elf could craft this.",
                            Image = "/images/Elf_Blade.png",
                            Level = 3,
                            Location = "Unobtainable",
                            Name = "Elf Blade",
                            PurchasePrice = 0,
                            SellPrice = 150,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba38"),
                            CriticalStrikeChance = ".02",
                            Damage = "27-40",
                            Description = "A brute s companion.",
                            Image = "/images/Kudgel.png",
                            Level = 4,
                            Location = "Unobtainable",
                            Name = "Kudgel",
                            PurchasePrice = 0,
                            SellPrice = 200,
                            Stats = " Speed (−1), Crit. Power (+4), Weight (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba39"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-25",
                            Description = "An elegant blade.",
                            Image = "/images/Rapier.png",
                            Level = 6,
                            Location = "Unobtainable",
                            Name = "Rapier",
                            PurchasePrice = 0,
                            SellPrice = 300,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba40"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "It brings back memories of Harvey s clinic.",
                            Image = "/images/Harvey%27s_Mallet.png",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Harvey s Mallet",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba41"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "A big, metal wrench. It smells like Maru.",
                            Image = "/images/Maru%27s_Wrench.png",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Maru s Wrench",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba42"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "Penny s favorite frying pan. There s some rubbery gunk stuck to the inside.",
                            Image = "/images/Penny%27s_Fryer.png",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Penny s Fryer",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba43"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "One of Sebastian s medieval replicas.",
                            Image = "/images/Seb%27s_Lost_Mace.png",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Seb s Lost Mace",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba44"),
                            CriticalStrikeChance = ".04",
                            Damage = "10-20",
                            Description = "When you hold the blade to your ear you can hear 1000 souls shrieking.",
                            Image = "/images/Shadow_Dagger.png",
                            Level = 8,
                            Location = "Unobtainable",
                            Name = "Shadow Dagger.",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba45"),
                            CriticalStrikeChance = ".02",
                            Damage = "26-42",
                            Description = "It s icy cold to the touch.",
                            Image = "/images/Yeti_Tooth.png",
                            Level = 9,
                            Location = "Unobtainable",
                            Name = "Yeti Tooth",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = "Defense (+4), Crit. Power (+10)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba46"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "It s searing hot and smells like Haley s hair.",
                            Image = "/images/Haley%27s_Iron.png",
                            Level = 13,
                            Location = "Unobtainable",
                            Name = "Haley s Iron",
                            PurchasePrice = 0,
                            SellPrice = 650,
                            Stats = " Speed (+154)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba47"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "It s made from fine marblewood.",
                            Image = "/images/Abby%27s_Planchette.png",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Abby s Planchette",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba48"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "Elliott used this to write his book. It s sharp!",
                            Image = "/images/Elliott%27s_Pencil.png",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Elliott s Pencil",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba49"),
                            CriticalStrikeChance = ".02",
                            Damage = "1-3",
                            Description = "Leah s favorite tool for shaping driftwood.",
                            Image = "/images/Leah%27s_Whittler.png",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Leah s Whittler",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba50"),
                            CriticalStrikeChance = ".02",
                            Damage = "≈4x that of a regular Slingshot using the same ammo",
                            Description = "It looks really powerful.",
                            Image = "/images/Galaxy_Slingshot.png",
                            Level = 0,
                            Location = "Unobtainable",
                            Name = "Galaxy Slingshot",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Slingshot"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba51"),
                            CriticalStrikeChance = ".02",
                            Damage = "Depends on ammo used",
                            Description = "Requires stones for ammo.",
                            Image = "/images/Slingshot.png",
                            Level = 0,
                            Location = "The Mines (Floor 40 chest reward)",
                            Name = "Slingshot",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Slingshot"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba52"),
                            CriticalStrikeChance = ".02",
                            Damage = "Depends on ammo used",
                            Description = "Requires stones for ammo.",
                            Image = "/images/Master_Slingshot.png",
                            Level = 0,
                            Location = "The Mines (Floor 70 chest reward)",
                            Name = "Master Slingshot",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Slingshot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
