// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StardewValleyAPI.API.DbContexts;

namespace StardewValleyAPI.Migrations
{
    [DbContext(typeof(StardewValleyLibraryContext))]
    partial class StardewValleyLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StardewValleyAPI.API.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriticalStrikeChance")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("Stats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc1b48df-c1da-4189-b0ff-b20fd4745025"),
                            CriticalStrikeChance = ".02",
                            Damage = "43953",
                            Description = "A rusty, dull old Sword.",
                            Level = 1,
                            Location = "The Mines entrance",
                            Name = "Rusty Sword",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("f51ffbd1-cab7-4b44-8f15-5924e53290c4"),
                            CriticalStrikeChance = ".02",
                            Damage = "44015",
                            Description = "Not bad for a piece of carved wood.",
                            Level = 2,
                            Location = "Adventurer s Guild",
                            Name = "Wooden Blade",
                            PurchasePrice = 250,
                            SellPrice = 100,
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("8d8c69a4-b8af-40e3-9576-a23200b5b4c4"),
                            CriticalStrikeChance = ".02",
                            Damage = "44047",
                            Description = "A standard metal blade.",
                            Level = 2,
                            Location = "The Mines floor 20 chest reward",
                            Name = "Steel SmallSword",
                            PurchasePrice = 0,
                            SellPrice = 100,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("fdc3f253-7240-4fb0-861b-3abe43e4d9e7"),
                            CriticalStrikeChance = ".02",
                            Damage = "42217",
                            Description = "Plated with silver to deter rust.",
                            Level = 3,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 20)",
                            Name = "Silver Saber",
                            PurchasePrice = 750,
                            SellPrice = 150,
                            Stats = "Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("a3d8dfd8-82dc-485a-997c-8f853826ab00"),
                            CriticalStrikeChance = ".02",
                            Damage = "41852",
                            Description = "It looks like a pirate owned this once.",
                            Level = 4,
                            Location = "The Mines (Floors 20+)",
                            Name = "Pirate s Sword",
                            PurchasePrice = 850,
                            SellPrice = 200,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("0176e4bb-b117-4c4d-aa67-dd823299bb4b"),
                            CriticalStrikeChance = ".02",
                            Damage = "42979",
                            Description = "A finely crafted blade.",
                            Level = 4,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 25)",
                            Name = "Cutlass",
                            PurchasePrice = 1500,
                            SellPrice = 200,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("68171d9f-f8dc-4a81-9e6f-90e4caac552b"),
                            CriticalStrikeChance = ".02",
                            Damage = "45992",
                            Description = "A heavy broadsword..",
                            Level = 4,
                            Location = "The Mines (Floors 40+)",
                            Name = "Iron Edge",
                            PurchasePrice = 0,
                            SellPrice = 200,
                            Stats = " Speed (−2), Defense (+1, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("5f62e113-257f-46e2-8575-9a10d24beee5"),
                            CriticalStrikeChance = ".02",
                            Damage = "43313",
                            Description = "Made powerful by forest magic.",
                            Level = 5,
                            Location = "The Mines (Floors 20-60)",
                            Name = "Forest Sword",
                            PurchasePrice = 0,
                            SellPrice = 250,
                            Stats = " Speed (+2), Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("c85027b9-4f1a-476a-9fc0-a916305f5959"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-24",
                            Description = "It feels hopeful to wield.",
                            Level = 5,
                            Location = "The Mines (Floors 60+)",
                            Name = "Holy Blade",
                            PurchasePrice = 0,
                            SellPrice = 250,
                            Stats = " Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("65ad031e-607a-4f12-91e1-b66724629c41"),
                            CriticalStrikeChance = ".04",
                            Damage = "44105",
                            Description = "Not very pleasant to wield.",
                            Level = 6,
                            Location = "Bug drop",
                            Name = "Insect Head",
                            PurchasePrice = 10000,
                            SellPrice = 300,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("ac68854d-c391-4dee-8ff9-d65438c9d18b"),
                            CriticalStrikeChance = ".02",
                            Damage = "20-32",
                            Description = "It s really heavy.",
                            Level = 6,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 45)",
                            Name = "Claymore",
                            PurchasePrice = 2000,
                            SellPrice = 300,
                            Stats = " Speed (−4), Defense (+2, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("c2424f3e-89a0-4d0b-a5e9-e4c07f1a681d"),
                            CriticalStrikeChance = "0",
                            Damage = "22-29",
                            Description = "It once belonged to an honorable knight.",
                            Level = 6,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 55)",
                            Name = "Templar s Blade",
                            PurchasePrice = 4000,
                            SellPrice = 300,
                            Stats = "Defense (+1)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("04b92ef1-2bd4-4118-b63d-51a9e11ecf65"),
                            CriticalStrikeChance = ".05",
                            Damage = "30-45",
                            Description = "It s glowing with vampire energy.",
                            Level = 8,
                            Location = "Haunted Skull drop",
                            Name = "Dark Sword",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = " Speed (-5, Weight (+5) ≈.08 chance of increasing Health, if it is below max.",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("179b9116-992d-4f89-bd94-8dd3a03d0bf9"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-35",
                            Description = "An heirloom from beyond the Gem Sea.",
                            Level = 7,
                            Location = "Fishing Treasure Chests (Fishing Level 2+)",
                            Name = "Neptune s Glaive",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (−1), Defense (+2, Weight (+4)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("1f613fd0-6374-45eb-a216-6acfc53bf5de"),
                            CriticalStrikeChance = ".02",
                            Damage = "29-44",
                            Description = "It looks like it could withstand anything.",
                            Level = 8,
                            Location = "Skull Cavern",
                            Name = "Tempered BroadSword",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = " Speed (−3), Defense (+3, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("93eb5480-1158-4ab8-a7da-a043793c2cda"),
                            CriticalStrikeChance = ".02",
                            Damage = "30-45",
                            Description = "It s incredibly sharp.",
                            Level = 9,
                            Location = "The Mines floor 90 chest reward",
                            Name = "Obsidian Edge",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = " Speed (−1), Crit. Power (+10)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("4560f39a-2515-4860-9de8-a28a0ef9ac64"),
                            CriticalStrikeChance = ".02",
                            Damage = "20-30",
                            Description = "A very light piece of sharpened bone.",
                            Level = 10,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 75)",
                            Name = "Bone Sword",
                            PurchasePrice = 6000,
                            SellPrice = 500,
                            Stats = " Speed (+4, Weight (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("bf1d9eb6-e893-47aa-ae49-847ff286a482"),
                            CriticalStrikeChance = ".02",
                            Damage = "26-38",
                            Description = "Light and powerful.",
                            Level = 14,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 90)",
                            Name = "Steel Falchion",
                            PurchasePrice = 9000,
                            SellPrice = 700,
                            Stats = " Speed (+4), Crit. Power (+20)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("4ddf8ba9-ac9c-4eec-9061-4cc6a95b6e81"),
                            CriticalStrikeChance = ".015",
                            Damage = "55-64",
                            Description = "A powerful blade forged in a pool of churning lava.",
                            Level = 15,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 120)",
                            Name = "Lava Katana",
                            PurchasePrice = 25000,
                            SellPrice = 750,
                            Stats = "Defense (+3), Crit. Power (+25, Weight (+3)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("74981378-6b4b-4593-b5f2-82988bb1310e"),
                            CriticalStrikeChance = ".02",
                            Damage = "60-80",
                            Description = "It s unlike anything you ve ever seen.",
                            Level = 26,
                            Location = "The Desert (bring a Prismatic Shard to the Three Pillars)",
                            Name = "Galaxy Sword",
                            PurchasePrice = 50000,
                            SellPrice = 1300,
                            Stats = " Speed (+4)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("48add9d6-0e2e-4c93-8663-aca12437c88b"),
                            CriticalStrikeChance = ".04",
                            Damage = "43891",
                            Description = "A small, light blade.",
                            Level = 2,
                            Location = "The Mines (Floors 1-20)",
                            Name = "Carving Knife",
                            PurchasePrice = 0,
                            SellPrice = 100,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("c939a1f9-79fd-488f-8b90-949d257b52ef"),
                            CriticalStrikeChance = ".03",
                            Damage = "43923",
                            Description = "A common Dagger.",
                            Level = 2,
                            Location = "Adventurer s Guild (after unlocking the Mines floor 15)",
                            Name = "Iron Dirk",
                            PurchasePrice = 500,
                            SellPrice = 100,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("7078e480-45c2-444e-8771-d9e1f6d7a0bd"),
                            CriticalStrikeChance = ".02",
                            Damage = "43952",
                            Description = "A swift little blade.",
                            Level = 3,
                            Location = "The Mines (Floors 21-40)",
                            Name = "Wind Spire",
                            PurchasePrice = 0,
                            SellPrice = 150,
                            Stats = "Crit. Power.png Crit. Power (+10, Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("11860c22-67e6-41e5-928c-ebd141abc694"),
                            CriticalStrikeChance = ".04",
                            Damage = "44172",
                            Description = "A weapon of choice for the swift and silent.",
                            Level = 8,
                            Location = "Skull Cavern (Serpents and crates)",
                            Name = "Burglar s Shank",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Stats = "Crit. Power.png Crit. Power (+25)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("50f5e25c-30f2-4537-9381-78b29c5cb425"),
                            CriticalStrikeChance = ".03",
                            Damage = "44108",
                            Description = "The blade is made of purified quartz.",
                            Level = 9,
                            Location = "The Mines floor 60 chest reward",
                            Name = "Crystal Dagger",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = "Crit. Power.png Crit. Power (+50, Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("5624b274-fe25-44d1-a9d6-e42b1a4a2dd0"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-26",
                            Description = "It came from the sea, but it s still sharp.",
                            Level = 11,
                            Location = "Fishing treasure chests",
                            Name = "Broken Trident",
                            PurchasePrice = 0,
                            SellPrice = 550,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("0057db11-44a9-4afc-bdd8-eb79f6ae911a"),
                            CriticalStrikeChance = ".06",
                            Damage = "24-30",
                            Description = "The blade is made of an iridium alloy.",
                            Level = 15,
                            Location = "Skull Cavern crates",
                            Name = "Wicked Kris",
                            PurchasePrice = 0,
                            SellPrice = 750,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("e5ac5261-0f9d-420d-b081-00cc210a4883"),
                            CriticalStrikeChance = ".02",
                            Damage = "30-40",
                            Description = "It s unlike anything you ve seen.",
                            Level = 20,
                            Location = "Adventurer s Guild (after obtaining the Galaxy Sword)",
                            Name = "Galaxy Dagger",
                            PurchasePrice = 35000,
                            SellPrice = 1000,
                            Stats = " Speed (+1, Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("41a2cb84-d0a5-4df7-a451-e19fa5128fd4"),
                            CriticalStrikeChance = ".02",
                            Damage = "06/nov",
                            Description = "An old, heavy bone caked in centuries of grime.",
                            Level = 1,
                            Location = "Found while digging outside the mines.",
                            Name = "Femur",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("0c8b4b60-d735-4e15-8b39-ba0bbe8f0019"),
                            CriticalStrikeChance = ".02",
                            Damage = "set/16",
                            Description = "A solid piece of wood, crudely chiseled into a Club shape.",
                            Level = 2,
                            Location = "The Mines (Floors 1-39)",
                            Name = "Wood Club.",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("8968da53-53d5-4953-b09d-8682e8898335"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-24",
                            Description = "The solid head packs a punch. Relatively light for a Club.",
                            Level = 2,
                            Location = "The Mines (Floors 40+)",
                            Name = "Wood Mallet",
                            PurchasePrice = 2000,
                            SellPrice = 0,
                            Stats = " Speed (+2, Weight (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("678723d2-8571-498a-9d60-ace8063549de"),
                            CriticalStrikeChance = ".02",
                            Damage = "18-27",
                            Description = "It s incredibly heavy.",
                            Level = 3,
                            Location = "The Mines (Floors 40+)",
                            Name = "Lead Rod",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (−4)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("c5dea295-ca95-4f19-8662-ed075940529f"),
                            CriticalStrikeChance = ".02",
                            Damage = "40-55",
                            Description = "An extremely heavy gavel that ll send foes flying.",
                            Level = 5,
                            Location = "Skull Cavern (Floors 40+)",
                            Name = "The Slammer",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Stats = " Speed (−2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("03564d64-fa92-4dee-b7fa-accdfc19a317"),
                            CriticalStrikeChance = ".02",
                            Damage = "70-90",
                            Description = "It s made from an ultra-light material you ve never seen before.",
                            Level = 9,
                            Location = "Adventurer s Guild (after obtaining the Galaxy Sword)",
                            Name = "Galaxy Hammer",
                            PurchasePrice = 75000,
                            SellPrice = 0,
                            Stats = " Speed (+2, Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("20637718-28d9-40e6-84c6-31c2c57c73cb"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "The sweet spot is dented from Alex s famous Grand Slam.",
                            Level = 1,
                            Location = "Unobtainable",
                            Name = "Alex s Bat",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Stats = " Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("3601697d-ebe4-40ea-aecc-ff63628eb8eb"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "It s seen better days.",
                            Level = 1,
                            Location = "Unobtainable",
                            Name = "Sam s Old Guitar",
                            PurchasePrice = 0,
                            SellPrice = 50,
                            Stats = " Speed (+1, Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("699cb176-163c-4648-9c9d-a9dbcc404b0f"),
                            CriticalStrikeChance = ".04",
                            Damage = "03/mai",
                            Description = "Only the nimble hands of an elf could craft this.",
                            Level = 3,
                            Location = "Unobtainable",
                            Name = "Elf Blade",
                            PurchasePrice = 0,
                            SellPrice = 150,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("8ea7e6d4-c0cb-4cbb-9c39-1cdd57a644af"),
                            CriticalStrikeChance = ".02",
                            Damage = "27-40",
                            Description = "A brute s companion.",
                            Level = 4,
                            Location = "Unobtainable",
                            Name = "Kudgel",
                            PurchasePrice = 0,
                            SellPrice = 200,
                            Stats = " Speed (−1), Crit. Power (+4), Weight (+2)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("37cf4560-9a19-4b91-a698-66c3a05eeae7"),
                            CriticalStrikeChance = ".02",
                            Damage = "15-25",
                            Description = "An elegant blade.",
                            Level = 6,
                            Location = "Unobtainable",
                            Name = "Rapier",
                            PurchasePrice = 0,
                            SellPrice = 300,
                            Stats = " Speed (+2)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("6aa33dcb-e212-47e4-b2d5-200a3ae7c568"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "It brings back memories of Harvey s clinic.",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Harvey s Mallet",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("96996b28-232d-4cbf-8d35-122de0a4b014"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "A big, metal wrench. It smells like Maru.",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Maru s Wrench",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("60b97bfd-1716-4a44-b4a5-162f6a441c14"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "Penny s favorite frying pan. There s some rubbery gunk stuck to the inside.",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Penny s Fryer",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("f9ccbff5-4e75-41d8-b856-929e814c0a85"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "One of Sebastian s medieval replicas.",
                            Level = 7,
                            Location = "Unobtainable",
                            Name = "Seb s Lost Mace",
                            PurchasePrice = 0,
                            SellPrice = 350,
                            Stats = " Speed (+158), Weight (+5)",
                            Type = "Club"
                        },
                        new
                        {
                            Id = new Guid("7cd589c5-1aab-42d1-a0ff-21322afde4f4"),
                            CriticalStrikeChance = ".04",
                            Damage = "out/20",
                            Description = "When you hold the blade to your ear you can hear 1000 souls shrieking.",
                            Level = 8,
                            Location = "Unobtainable",
                            Name = "Shadow Dagger.",
                            PurchasePrice = 0,
                            SellPrice = 400,
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("bc327d42-5aae-4dcf-b6fe-0e84e4e5f7a6"),
                            CriticalStrikeChance = ".02",
                            Damage = "26-42",
                            Description = "It s icy cold to the touch.",
                            Level = 9,
                            Location = "Unobtainable",
                            Name = "Yeti Tooth",
                            PurchasePrice = 0,
                            SellPrice = 450,
                            Stats = "Defense (+4), Crit. Power (+10)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("3a33488f-d877-48b3-a229-8ff2a07f5ca8"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "It s searing hot and smells like Haley s hair.",
                            Level = 13,
                            Location = "Unobtainable",
                            Name = "Haley s Iron",
                            PurchasePrice = 0,
                            SellPrice = 650,
                            Stats = " Speed (+154)",
                            Type = "Sword"
                        },
                        new
                        {
                            Id = new Guid("7bc928ce-903e-441e-be1d-5a1ef413fcc9"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "It s made from fine marblewood.",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Abby s Planchette",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("7d044764-0ec3-4741-ac93-2725979feccf"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "Elliott used this to write his book. It s sharp!",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Elliott s Pencil",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("dd4fcb78-b4a1-401b-a39f-54231431e0f8"),
                            CriticalStrikeChance = ".02",
                            Damage = "01/mar",
                            Description = "Leah s favorite tool for shaping driftwood.",
                            Level = 14,
                            Location = "Unobtainable",
                            Name = "Leah s Whittler",
                            PurchasePrice = 0,
                            SellPrice = 700,
                            Stats = " Speed (+154), Weight (+5)",
                            Type = "Dagger"
                        },
                        new
                        {
                            Id = new Guid("31f5f91f-8c03-4ddc-988e-60425260a8ad"),
                            CriticalStrikeChance = ".02",
                            Damage = "≈4x that of a regular WeaponType.Slingshot.ToString() using the same ammo",
                            Description = "It looks really powerful.",
                            Level = 0,
                            Location = "Unobtainable",
                            Name = "Galaxy Slingshot",
                            PurchasePrice = 0,
                            SellPrice = 0,
                            Type = "Slingshot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
