using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StardewValleyAPI.API.Entities;
using StardewValleyAPI.Entities;
using StardewValleyAPI.Entities.Model;

namespace StardewValleyAPI.API.DbContexts {
    public class StardewValleyLibraryContext : DbContext {
        public StardewValleyLibraryContext (DbContextOptions<StardewValleyLibraryContext> options) : base (options) { }

        public DbSet<Weapon> Weapons { get; set; }

        protected override void OnModelCreating (ModelBuilder modelBuilder) {
            // seed the database with dummy data
            modelBuilder.Entity<Weapon> ().HasData (

                new Weapon () {  Id = Guid.NewGuid(), Name = "Rusty Sword", Type = WeaponType.Sword.ToString (), Level = 1, Description = "A rusty, dull old Sword.", Damage = "43953", CriticalStrikeChance = ".02", Location = "The Mines entrance", SellPrice = 50 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Wooden Blade", Type = WeaponType.Sword.ToString (), Level = 2, Description = "Not bad for a piece of carved wood.", Damage = "44015", CriticalStrikeChance = ".02", Location = "Adventurer s Guild", PurchasePrice = 250, SellPrice = 100 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Steel SmallSword", Type = WeaponType.Sword.ToString (), Level = 2, Description = "A standard metal blade.", Damage = "44047", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "The Mines floor 20 chest reward", SellPrice = 100 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Silver Saber", Type = WeaponType.Sword.ToString (), Level = 3, Description = "Plated with silver to deter rust.", Damage = "42217", CriticalStrikeChance = ".02", Stats = "Defense (+1)", Location = "Adventurer s Guild (after unlocking the Mines floor 20)", PurchasePrice = 750, SellPrice = 150 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Pirate s Sword", Type = WeaponType.Sword.ToString (), Level = 4, Description = "It looks like a pirate owned this once.", Damage = "41852", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "The Mines (Floors 20+)", PurchasePrice = 850, SellPrice = 200 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Cutlass", Type = WeaponType.Sword.ToString (), Level = 4, Description = "A finely crafted blade.", Damage = "42979", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Adventurer s Guild (after unlocking the Mines floor 25)", PurchasePrice = 1500, SellPrice = 200 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Iron Edge", Type = WeaponType.Sword.ToString (), Level = 4, Description = "A heavy broadsword..", Damage = "45992", CriticalStrikeChance = ".02", Stats = " Speed (−2), Defense (+1, Weight (+3)", Location = "The Mines (Floors 40+)", SellPrice = 200 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Forest Sword", Type = WeaponType.Sword.ToString (), Level = 5, Description = "Made powerful by forest magic.", Damage = "43313", CriticalStrikeChance = ".02", Stats = " Speed (+2), Defense (+1)", Location = "The Mines (Floors 20-60)", SellPrice = 250 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Holy Blade", Type = WeaponType.Sword.ToString (), Level = 5, Description = "It feels hopeful to wield.", Damage = "18-24", CriticalStrikeChance = ".02", Stats = " Weight (+3)", Location = "The Mines (Floors 60+)", SellPrice = 250 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Insect Head", Type = WeaponType.Sword.ToString (), Level = 6, Description = "Not very pleasant to wield.", Damage = "44105", CriticalStrikeChance = ".04", Stats = " Speed (+2)", Location = "Bug drop", PurchasePrice = 10000, SellPrice = 300 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Claymore", Type = WeaponType.Sword.ToString (), Level = 6, Description = "It s really heavy.", Damage = "20-32", CriticalStrikeChance = ".02", Stats = " Speed (−4), Defense (+2, Weight (+3)", Location = "Adventurer s Guild (after unlocking the Mines floor 45)", PurchasePrice = 2000, SellPrice = 300 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Templar s Blade", Type = WeaponType.Sword.ToString (), Level = 6, Description = "It once belonged to an honorable knight.", Damage = "22-29", CriticalStrikeChance = "0", Stats = "Defense (+1)", Location = "Adventurer s Guild (after unlocking the Mines floor 55)", PurchasePrice = 4000, SellPrice = 300 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Dark Sword", Type = WeaponType.Sword.ToString (), Level = 8, Description = "It s glowing with vampire energy.", Damage = "30-45", CriticalStrikeChance = ".05", Stats = " Speed (-5, Weight (+5) ≈.08 chance of increasing Health, if it is below max.", Location = "Haunted Skull drop", SellPrice = 400 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Neptune s Glaive", Type = WeaponType.Sword.ToString (), Level = 7, Description = "An heirloom from beyond the Gem Sea.", Damage = "18-35", CriticalStrikeChance = ".02", Stats = " Speed (−1), Defense (+2, Weight (+4)", Location = "Fishing Treasure Chests (Fishing Level 2+)", SellPrice = 350 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Tempered BroadSword", Type = WeaponType.Sword.ToString (), Level = 8, Description = "It looks like it could withstand anything.", Damage = "29-44", CriticalStrikeChance = ".02", Stats = " Speed (−3), Defense (+3, Weight (+3)", Location = "Skull Cavern", SellPrice = 400 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Obsidian Edge", Type = WeaponType.Sword.ToString (), Level = 9, Description = "It s incredibly sharp.", Damage = "30-45", CriticalStrikeChance = ".02", Stats = " Speed (−1), Crit. Power (+10)", Location = "The Mines floor 90 chest reward", SellPrice = 450 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Bone Sword", Type = WeaponType.Sword.ToString (), Level = 10, Description = "A very light piece of sharpened bone.", Damage = "20-30", CriticalStrikeChance = ".02", Stats = " Speed (+4, Weight (+2)", Location = "Adventurer s Guild (after unlocking the Mines floor 75)", PurchasePrice = 6000, SellPrice = 500 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Steel Falchion", Type = WeaponType.Sword.ToString (), Level = 14, Description = "Light and powerful.", Damage = "26-38", CriticalStrikeChance = ".02", Stats = " Speed (+4), Crit. Power (+20)", Location = "Adventurer s Guild (after unlocking the Mines floor 90)", PurchasePrice = 9000, SellPrice = 700 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Lava Katana", Type = WeaponType.Sword.ToString (), Level = 15, Description = "A powerful blade forged in a pool of churning lava.", Damage = "55-64", CriticalStrikeChance = ".015", Stats = "Defense (+3), Crit. Power (+25, Weight (+3)", Location = "Adventurer s Guild (after unlocking the Mines floor 120)", PurchasePrice = 25000, SellPrice = 750 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Galaxy Sword", Type = WeaponType.Sword.ToString (), Level = 26, Description = "It s unlike anything you ve ever seen.", Damage = "60-80", CriticalStrikeChance = ".02", Stats = " Speed (+4)", Location = "The Desert (bring a Prismatic Shard to the Three Pillars)", PurchasePrice = 50000, SellPrice = 1300 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Carving Knife", Type = WeaponType.Dagger.ToString (), Level = 2, Description = "A small, light blade.", Damage = "43891", CriticalStrikeChance = ".04", Location = "The Mines (Floors 1-20)", SellPrice = 100 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Iron Dirk", Type = WeaponType.Dagger.ToString (), Level = 2, Description = "A common Dagger.", Damage = "43923", CriticalStrikeChance = ".03", Location = "Adventurer s Guild (after unlocking the Mines floor 15)", PurchasePrice = 500, SellPrice = 100 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Wind Spire", Type = WeaponType.Dagger.ToString (), Level = 3, Description = "A swift little blade.", Damage = "43952", CriticalStrikeChance = ".02", Stats = "Crit. Power.png Crit. Power (+10, Weight (+5)", Location = "The Mines (Floors 21-40)", SellPrice = 150 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Burglar s Shank", Type = WeaponType.Dagger.ToString (), Level = 8, Description = "A weapon of choice for the swift and silent.", Damage = "44172", CriticalStrikeChance = ".04", Stats = "Crit. Power.png Crit. Power (+25)", Location = "Skull Cavern (Serpents and crates)", SellPrice = 400 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Crystal Dagger", Type = WeaponType.Dagger.ToString (), Level = 9, Description = "The blade is made of purified quartz.", Damage = "44108", CriticalStrikeChance = ".03", Stats = "Crit. Power.png Crit. Power (+50, Weight (+5)", Location = "The Mines floor 60 chest reward", SellPrice = 450 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Broken Trident", Type = WeaponType.Dagger.ToString (), Level = 11, Description = "It came from the sea, but it s still sharp.", Damage = "15-26", CriticalStrikeChance = ".02", Location = "Fishing treasure chests", SellPrice = 550 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Wicked Kris", Type = WeaponType.Dagger.ToString (), Level = 15, Description = "The blade is made of an iridium alloy.", Damage = "24-30", CriticalStrikeChance = ".06", Location = "Skull Cavern crates", SellPrice = 750 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Galaxy Dagger", Type = WeaponType.Dagger.ToString (), Level = 20, Description = "It s unlike anything you ve seen.", Damage = "30-40", CriticalStrikeChance = ".02", Stats = " Speed (+1, Weight (+5)", Location = "Adventurer s Guild (after obtaining the Galaxy Sword)", PurchasePrice = 35000, SellPrice = 1000 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Femur", Type = WeaponType.Club.ToString (), Level = 1, Description = "An old, heavy bone caked in centuries of grime.", Damage = "06/nov", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Found while digging outside the mines." },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Wood Club.", Type = WeaponType.Club.ToString (), Level = 2, Description = "A solid piece of wood, crudely chiseled into a Club shape.", Damage = "set/16", CriticalStrikeChance = ".02", Location = "The Mines (Floors 1-39)" },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Wood Mallet", Type = WeaponType.Club.ToString (), Level = 2, Description = "The solid head packs a punch. Relatively light for a Club.", Damage = "15-24", CriticalStrikeChance = ".02", Stats = " Speed (+2, Weight (+2)", Location = "The Mines (Floors 40+)", PurchasePrice = 2000 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Lead Rod", Type = WeaponType.Club.ToString (), Level = 3, Description = "It s incredibly heavy.", Damage = "18-27", CriticalStrikeChance = ".02", Stats = " Speed (−4)", Location = "The Mines (Floors 40+)" },
                new Weapon () {  Id = Guid.NewGuid(),Name = "The Slammer", Type = WeaponType.Club.ToString (), Level = 5, Description = "An extremely heavy gavel that ll send foes flying.", Damage = "40-55", CriticalStrikeChance = ".02", Stats = " Speed (−2)", Location = "Skull Cavern (Floors 40+)" },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Galaxy Hammer", Type = WeaponType.Club.ToString (), Level = 9, Description = "It s made from an ultra-light material you ve never seen before.", Damage = "70-90", CriticalStrikeChance = ".02", Stats = " Speed (+2, Weight (+5)", Location = "Adventurer s Guild (after obtaining the Galaxy Sword)", PurchasePrice = 75000 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Alex s Bat", Type = WeaponType.Club.ToString (), Level = 1, Description = "The sweet spot is dented from Alex s famous Grand Slam.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Weight (+5)", Location = "Unobtainable", SellPrice = 50 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Sam s Old Guitar", Type = WeaponType.Club.ToString (), Level = 1, Description = "It s seen better days.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+1, Weight (+5)", Location = "Unobtainable", SellPrice = 50 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Elf Blade", Type = WeaponType.Dagger.ToString (), Level = 3, Description = "Only the nimble hands of an elf could craft this.", Damage = "03/mai", CriticalStrikeChance = ".04", Location = "Unobtainable", SellPrice = 150 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Kudgel", Type = WeaponType.Club.ToString (), Level = 4, Description = "A brute s companion.", Damage = "27-40", CriticalStrikeChance = ".02", Stats = " Speed (−1), Crit. Power (+4), Weight (+2)", Location = "Unobtainable", SellPrice = 200 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Rapier", Type = WeaponType.Sword.ToString (), Level = 6, Description = "An elegant blade.", Damage = "15-25", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Unobtainable", SellPrice = 300 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Harvey s Mallet", Type = WeaponType.Club.ToString (), Level = 7, Description = "It brings back memories of Harvey s clinic.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Maru s Wrench", Type = WeaponType.Club.ToString (), Level = 7, Description = "A big, metal wrench. It smells like Maru.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Penny s Fryer", Type = WeaponType.Club.ToString (), Level = 7, Description = "Penny s favorite frying pan. There s some rubbery gunk stuck to the inside.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Seb s Lost Mace", Type = WeaponType.Club.ToString (), Level = 7, Description = "One of Sebastian s medieval replicas.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Shadow Dagger.", Type = WeaponType.Dagger.ToString (), Level = 8, Description = "When you hold the blade to your ear you can hear 1000 souls shrieking.", Damage = "out/20", CriticalStrikeChance = ".04", Location = "Unobtainable", SellPrice = 400 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Yeti Tooth", Type = WeaponType.Sword.ToString (), Level = 9, Description = "It s icy cold to the touch.", Damage = "26-42", CriticalStrikeChance = ".02", Stats = "Defense (+4), Crit. Power (+10)", Location = "Unobtainable", SellPrice = 450 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Haley s Iron", Type = WeaponType.Sword.ToString (), Level = 13, Description = "It s searing hot and smells like Haley s hair.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+154)", Location = "Unobtainable", SellPrice = 650 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Abby s Planchette", Type = WeaponType.Dagger.ToString (), Level = 14, Description = "It s made from fine marblewood.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Elliott s Pencil", Type = WeaponType.Dagger.ToString (), Level = 14, Description = "Elliott used this to write his book. It s sharp!", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Leah s Whittler", Type = WeaponType.Dagger.ToString (), Level = 14, Description = "Leah s favorite tool for shaping driftwood.", Damage = "01/mar", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
                new Weapon () {  Id = Guid.NewGuid(),Name = "Galaxy Slingshot", Type = WeaponType.Slingshot.ToString (), Description = "It looks really powerful.", Damage = "≈4x that of a regular WeaponType.Slingshot.ToString() using the same ammo", CriticalStrikeChance = ".02", Location = "Unobtainable" }

            );

            base.OnModelCreating (modelBuilder);
        }
    }
}