using System;
using System.Collections.Generic;
using System.Web;
using Microsoft.EntityFrameworkCore;
using StardewValleyAPI.API.Entities;
using StardewValleyAPI.Entities;
using StardewValleyAPI.Entities.Model;

namespace StardewValleyAPI.API.DbContexts
{
    public class StardewValleyLibraryContext : DbContext
    {
        public StardewValleyLibraryContext(DbContextOptions<StardewValleyLibraryContext> options) : base(options) { }

        public DbSet<Weapon> Weapons { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // seed the database with dummy data
            modelBuilder.Entity<Weapon>().HasData(
                new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba01"), Image = "/images/" + HttpUtility.UrlEncode("Rusty_Sword.png"), Name = "Rusty Sword", Type = WeaponType.Sword.ToString(), Level = 1, Description = "A rusty, dull old Sword.", Damage = "2-5", CriticalStrikeChance = ".02", Location = "The Mines entrance", SellPrice = 50 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba02"), Image = "/images/" + HttpUtility.UrlEncode("Wooden_Blade.png"), Name = "Wooden Blade", Type = WeaponType.Sword.ToString(), Level = 2, Description = "Not bad for a piece of carved wood.", Damage = "3-7", CriticalStrikeChance = ".02", Location = "Adventurer s Guild", PurchasePrice = 250, SellPrice = 100 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba03"), Image = "/images/" + HttpUtility.UrlEncode("Steel_Smallsword.png"), Name = "Steel SmallSword", Type = WeaponType.Sword.ToString(), Level = 2, Description = "A standard metal blade.", Damage = "4-8", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "The Mines floor 20 chest reward", SellPrice = 100 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba04"), Image = "/images/" + HttpUtility.UrlEncode("Silver_Saber.png"), Name = "Silver Saber", Type = WeaponType.Sword.ToString(), Level = 3, Description = "Plated with silver to deter rust.", Damage = "8-15", CriticalStrikeChance = ".02", Stats = "Defense (+1)", Location = "Adventurer s Guild (after unlocking the Mines floor 20)", PurchasePrice = 750, SellPrice = 150 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba05"), Image = "/images/" + HttpUtility.UrlEncode("Pirate's_Sword.png"), Name = "Pirate s Sword", Type = WeaponType.Sword.ToString(), Level = 4, Description = "It looks like a pirate owned this once.", Damage = "8-14", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "The Mines (Floors 20+)", PurchasePrice = 850, SellPrice = 200 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba06"), Image = "/images/" + HttpUtility.UrlEncode("Cutlass.png"), Name = "Cutlass", Type = WeaponType.Sword.ToString(), Level = 4, Description = "A finely crafted blade.", Damage = "9-17", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Adventurer s Guild (after unlocking the Mines floor 25)", PurchasePrice = 1500, SellPrice = 200 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba07"), Image = "/images/" + HttpUtility.UrlEncode("Iron_Edge.png"), Name = "Iron Edge", Type = WeaponType.Sword.ToString(), Level = 4, Description = "A heavy broadsword..", Damage = "12-25", CriticalStrikeChance = ".02", Stats = " Speed (−2), Defense (+1), Weight (+3)", Location = "The Mines (Floors 40+)", SellPrice = 200 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba08"), Image = "/images/" + HttpUtility.UrlEncode("Forest_Sword.png"), Name = "Forest Sword", Type = WeaponType.Sword.ToString(), Level = 5, Description = "Made powerful by forest magic.", Damage = "8-18", CriticalStrikeChance = ".02", Stats = " Speed (+2), Defense (+1)", Location = "The Mines (Floors 20-60)", SellPrice = 250 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba09"), Image = "/images/" + HttpUtility.UrlEncode("Holy_Blade.png"), Name = "Holy Blade", Type = WeaponType.Sword.ToString(), Level = 5, Description = "It feels hopeful to wield.", Damage = "18-24", CriticalStrikeChance = ".02", Stats = " Weight (+3)", Location = "The Mines (Floors 60+)", SellPrice = 250 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba10"), Image = "/images/" + HttpUtility.UrlEncode("Insect_Head.png"), Name = "Insect Head", Type = WeaponType.Sword.ToString(), Level = 6, Description = "Not very pleasant to wield.", Damage = "10-20", CriticalStrikeChance = ".04", Stats = " Speed (+2)", Location = "Bug drop", PurchasePrice = 10000, SellPrice = 300 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba11"), Image = "/images/" + HttpUtility.UrlEncode("Claymore.png"), Name = "Claymore", Type = WeaponType.Sword.ToString(), Level = 6, Description = "It s really heavy.", Damage = "20-32", CriticalStrikeChance = ".02", Stats = " Speed (−4), Defense (+2, Weight (+3)", Location = "Adventurer s Guild (after unlocking the Mines floor 45)", PurchasePrice = 2000, SellPrice = 300 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba12"), Image = "/images/" + HttpUtility.UrlEncode("Templar's_Blade.png"), Name = "Templar s Blade", Type = WeaponType.Sword.ToString(), Level = 6, Description = "It once belonged to an honorable knight.", Damage = "22-29", CriticalStrikeChance = "0", Stats = "Defense (+1)", Location = "Adventurer s Guild (after unlocking the Mines floor 55)", PurchasePrice = 4000, SellPrice = 300 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba13"), Image = "/images/" + HttpUtility.UrlEncode("Dark_Sword.png"), Name = "Dark Sword", Type = WeaponType.Sword.ToString(), Level = 8, Description = "It s glowing with vampire energy.", Damage = "30-45", CriticalStrikeChance = ".05", Stats = " Speed (-5, Weight (+5) ≈.08 chance of increasing Health, if it is below max.", Location = "Haunted Skull drop", SellPrice = 400 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba14"), Image = "/images/" + HttpUtility.UrlEncode("Neptune's_Glaive.png"), Name = "Neptune s Glaive", Type = WeaponType.Sword.ToString(), Level = 7, Description = "An heirloom from beyond the Gem Sea.", Damage = "18-35", CriticalStrikeChance = ".02", Stats = " Speed (−1), Defense (+2, Weight (+4)", Location = "Fishing Treasure Chests (Fishing Level 2+)", SellPrice = 350 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba15"), Image = "/images/" + HttpUtility.UrlEncode("Tempered_Broadsword.png"), Name = "Tempered BroadSword", Type = WeaponType.Sword.ToString(), Level = 8, Description = "It looks like it could withstand anything.", Damage = "29-44", CriticalStrikeChance = ".02", Stats = " Speed (−3), Defense (+3, Weight (+3)", Location = "Skull Cavern", SellPrice = 400 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba16"), Image = "/images/" + HttpUtility.UrlEncode("Obsidian_Edge.png"), Name = "Obsidian Edge", Type = WeaponType.Sword.ToString(), Level = 9, Description = "It s incredibly sharp.", Damage = "30-45", CriticalStrikeChance = ".02", Stats = " Speed (−1), Crit. Power (+10)", Location = "The Mines floor 90 chest reward", SellPrice = 450 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba17"), Image = "/images/" + HttpUtility.UrlEncode("Bone_Sword.png"), Name = "Bone Sword", Type = WeaponType.Sword.ToString(), Level = 10, Description = "A very light piece of sharpened bone.", Damage = "20-30", CriticalStrikeChance = ".02", Stats = " Speed (+4, Weight (+2)", Location = "Adventurer s Guild (after unlocking the Mines floor 75)", PurchasePrice = 6000, SellPrice = 500 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba18"), Image = "/images/" + HttpUtility.UrlEncode("Steel_Falchion.png"), Name = "Steel Falchion", Type = WeaponType.Sword.ToString(), Level = 14, Description = "Light and powerful.", Damage = "28-46", CriticalStrikeChance = ".02", Stats = " Speed (+4), Crit. Power (+20)", Location = "Adventurer s Guild (after unlocking the Mines floor 90)", PurchasePrice = 9000, SellPrice = 700 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba19"), Image = "/images/" + HttpUtility.UrlEncode("Lava_Katana.png"), Name = "Lava Katana", Type = WeaponType.Sword.ToString(), Level = 15, Description = "A powerful blade forged in a pool of churning lava.", Damage = "55-64", CriticalStrikeChance = ".015", Stats = "Defense (+3), Crit. Power (+25, Weight (+3)", Location = "Adventurer s Guild (after unlocking the Mines floor 120)", PurchasePrice = 25000, SellPrice = 750 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba20"), Image = "/images/" + HttpUtility.UrlEncode("Galaxy_Sword.png"), Name = "Galaxy Sword", Type = WeaponType.Sword.ToString(), Level = 26, Description = "It s unlike anything you ve ever seen.", Damage = "60-80", CriticalStrikeChance = ".02", Stats = " Speed (+4)", Location = "The Desert (bring a Prismatic Shard to the Three Pillars)", PurchasePrice = 50000, SellPrice = 1300 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba21"), Image = "/images/" + HttpUtility.UrlEncode("Carving_Knife.png"), Name = "Carving Knife", Type = WeaponType.Dagger.ToString(), Level = 2, Description = "A small, light blade.", Damage = "1-3", CriticalStrikeChance = ".04", Location = "The Mines (Floors 1-20)", SellPrice = 100 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba22"), Image = "/images/" + HttpUtility.UrlEncode("Iron_Dirk.png"), Name = "Iron Dirk", Type = WeaponType.Dagger.ToString(), Level = 2, Description = "A common Dagger.", Damage = "2-4", CriticalStrikeChance = ".03", Location = "Adventurer s Guild (after unlocking the Mines floor 15)", PurchasePrice = 500, SellPrice = 100 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba23"), Image = "/images/" + HttpUtility.UrlEncode("Wind_Spire.png"), Name = "Wind Spire", Type = WeaponType.Dagger.ToString(), Level = 3, Description = "A swift little blade.", Damage = "1-5", CriticalStrikeChance = ".02", Stats = " Crit. Power (+10), Weight (+5)", Location = "The Mines (Floors 21-40)", SellPrice = 150 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba24"), Image = "/images/" + HttpUtility.UrlEncode("Burglar's_Shank.png"), Name = "Burglar s Shank", Type = WeaponType.Dagger.ToString(), Level = 8, Description = "A weapon of choice for the swift and silent.", Damage = "7-12", CriticalStrikeChance = ".04", Stats = " Crit. Power (+25)", Location = "Skull Cavern (Serpents and crates)", SellPrice = 400 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba25"), Image = "/images/" + HttpUtility.UrlEncode("Crystal_Dagger.png"), Name = "Crystal Dagger", Type = WeaponType.Dagger.ToString(), Level = 9, Description = "The blade is made of purified quartz.", Damage = "4-10", CriticalStrikeChance = ".03", Stats = " Crit. Power (+50, Weight (+5)", Location = "The Mines floor 60 chest reward", SellPrice = 450 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba26"), Image = "/images/" + HttpUtility.UrlEncode("Broken_Trident.png"), Name = "Broken Trident", Type = WeaponType.Dagger.ToString(), Level = 11, Description = "It came from the sea, but it s still sharp.", Damage = "15-26", CriticalStrikeChance = ".02", Location = "Fishing treasure chests", SellPrice = 550 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba27"), Image = "/images/" + HttpUtility.UrlEncode("Wicked_Kris.png"), Name = "Wicked Kris", Type = WeaponType.Dagger.ToString(), Level = 15, Description = "The blade is made of an iridium alloy.", Damage = "24-30", CriticalStrikeChance = ".06", Location = "Skull Cavern crates", SellPrice = 750 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba28"), Image = "/images/" + HttpUtility.UrlEncode("Galaxy_Dagger.png"), Name = "Galaxy Dagger", Type = WeaponType.Dagger.ToString(), Level = 20, Description = "It s unlike anything you ve seen.", Damage = "30-40", CriticalStrikeChance = ".02", Stats = " Speed (+1), Weight (+5)", Location = "Adventurer s Guild (after obtaining the Galaxy Sword)", PurchasePrice = 35000, SellPrice = 1000 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba29"), Image = "/images/" + HttpUtility.UrlEncode("Femur.png"), Name = "Femur", Type = WeaponType.Club.ToString(), Level = 1, Description = "An old, heavy bone caked in centuries of grime.", Damage = "6-11", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Found while digging outside the mines." },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba30"), Image = "/images/" + HttpUtility.UrlEncode("Wood_Club.png"), Name = "Wood Club.", Type = WeaponType.Club.ToString(), Level = 2, Description = "A solid piece of wood, crudely chiseled into a Club shape.", Damage = "9-16", CriticalStrikeChance = ".02", Location = "The Mines (Floors 1-39)" },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba31"), Image = "/images/" + HttpUtility.UrlEncode("Wood_Mallet.png"), Name = "Wood Mallet", Type = WeaponType.Club.ToString(), Level = 2, Description = "The solid head packs a punch. Relatively light for a Club.", Damage = "15-24", CriticalStrikeChance = ".02", Stats = " Speed (+2, Weight (+2)", Location = "The Mines (Floors 40+)", PurchasePrice = 2000 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba32"), Image = "/images/" + HttpUtility.UrlEncode("Lead_Rod.png"), Name = "Lead Rod", Type = WeaponType.Club.ToString(), Level = 3, Description = "It s incredibly heavy.", Damage = "18-27", CriticalStrikeChance = ".02", Stats = " Speed (−4)", Location = "The Mines (Floors 40+)" },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba33"), Image = "/images/" + HttpUtility.UrlEncode("The_Slammer.png"), Name = "The Slammer", Type = WeaponType.Club.ToString(), Level = 5, Description = "An extremely heavy gavel that ll send foes flying.", Damage = "40-55", CriticalStrikeChance = ".02", Stats = " Speed (−2)", Location = "Skull Cavern (Floors 40+)" },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba34"), Image = "/images/" + HttpUtility.UrlEncode("Galaxy_Hammer.png"), Name = "Galaxy Hammer", Type = WeaponType.Club.ToString(), Level = 9, Description = "It s made from an ultra-light material you ve never seen before.", Damage = "70-90", CriticalStrikeChance = ".02", Stats = " Speed (+2, Weight (+5)", Location = "Adventurer s Guild (after obtaining the Galaxy Sword)", PurchasePrice = 75000 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba35"), Image = "/images/" + HttpUtility.UrlEncode("Alex's_Bat.png"), Name = "Alex s Bat", Type = WeaponType.Club.ToString(), Level = 1, Description = "The sweet spot is dented from Alex s famous Grand Slam.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Weight (+5)", Location = "Unobtainable", SellPrice = 50 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba36"), Image = "/images/" + HttpUtility.UrlEncode("Sam's_Old_Guitar.png"), Name = "Sam s Old Guitar", Type = WeaponType.Club.ToString(), Level = 1, Description = "It s seen better days.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+1), Weight (+5)", Location = "Unobtainable", SellPrice = 50 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba37"), Image = "/images/" + HttpUtility.UrlEncode("Elf_Blade.png"), Name = "Elf Blade", Type = WeaponType.Dagger.ToString(), Level = 3, Description = "Only the nimble hands of an elf could craft this.", Damage = "3-5", CriticalStrikeChance = ".04", Location = "Unobtainable", SellPrice = 150 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba38"), Image = "/images/" + HttpUtility.UrlEncode("Kudgel.png"), Name = "Kudgel", Type = WeaponType.Club.ToString(), Level = 4, Description = "A brute s companion.", Damage = "27-40", CriticalStrikeChance = ".02", Stats = " Speed (−1), Crit. Power (+4), Weight (+2)", Location = "Unobtainable", SellPrice = 200 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba39"), Image = "/images/" + HttpUtility.UrlEncode("Rapier.png"), Name = "Rapier", Type = WeaponType.Sword.ToString(), Level = 6, Description = "An elegant blade.", Damage = "15-25", CriticalStrikeChance = ".02", Stats = " Speed (+2)", Location = "Unobtainable", SellPrice = 300 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba40"), Image = "/images/" + HttpUtility.UrlEncode("Harvey's_Mallet.png"), Name = "Harvey s Mallet", Type = WeaponType.Club.ToString(), Level = 7, Description = "It brings back memories of Harvey s clinic.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba41"), Image = "/images/" + HttpUtility.UrlEncode("Maru's_Wrench.png"), Name = "Maru s Wrench", Type = WeaponType.Club.ToString(), Level = 7, Description = "A big, metal wrench. It smells like Maru.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba42"), Image = "/images/" + HttpUtility.UrlEncode("Penny's_Fryer.png"), Name = "Penny s Fryer", Type = WeaponType.Club.ToString(), Level = 7, Description = "Penny s favorite frying pan. There s some rubbery gunk stuck to the inside.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba43"), Image = "/images/" + HttpUtility.UrlEncode("Seb's_Lost_Mace.png"), Name = "Seb s Lost Mace", Type = WeaponType.Club.ToString(), Level = 7, Description = "One of Sebastian s medieval replicas.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+158), Weight (+5)", Location = "Unobtainable", SellPrice = 350 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba44"), Image = "/images/" + HttpUtility.UrlEncode("Shadow_Dagger.png"), Name = "Shadow Dagger.", Type = WeaponType.Dagger.ToString(), Level = 8, Description = "When you hold the blade to your ear you can hear 1000 souls shrieking.", Damage = "10-20", CriticalStrikeChance = ".04", Location = "Unobtainable", SellPrice = 400 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba45"), Image = "/images/" + HttpUtility.UrlEncode("Yeti_Tooth.png"), Name = "Yeti Tooth", Type = WeaponType.Sword.ToString(), Level = 9, Description = "It s icy cold to the touch.", Damage = "26-42", CriticalStrikeChance = ".02", Stats = "Defense (+4), Crit. Power (+10)", Location = "Unobtainable", SellPrice = 450 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba46"), Image = "/images/" + HttpUtility.UrlEncode("Haley's_Iron.png"), Name = "Haley s Iron", Type = WeaponType.Sword.ToString(), Level = 13, Description = "It s searing hot and smells like Haley s hair.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+154)", Location = "Unobtainable", SellPrice = 650 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba47"), Image = "/images/" + HttpUtility.UrlEncode("Abby's_Planchette.png"), Name = "Abby s Planchette", Type = WeaponType.Dagger.ToString(), Level = 14, Description = "It s made from fine marblewood.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba48"), Image = "/images/" + HttpUtility.UrlEncode("Elliott's_Pencil.png"), Name = "Elliott s Pencil", Type = WeaponType.Dagger.ToString(), Level = 14, Description = "Elliott used this to write his book. It s sharp!", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba49"), Image = "/images/" + HttpUtility.UrlEncode("Leah's_Whittler.png"), Name = "Leah s Whittler", Type = WeaponType.Dagger.ToString(), Level = 14, Description = "Leah s favorite tool for shaping driftwood.", Damage = "1-3", CriticalStrikeChance = ".02", Stats = " Speed (+154), Weight (+5)", Location = "Unobtainable", SellPrice = 700 },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba50"), Image = "/images/" + HttpUtility.UrlEncode("Galaxy_Slingshot.png"), Name = "Galaxy Slingshot", Type = WeaponType.Slingshot.ToString(), Description = "It looks really powerful.", Damage = "≈4x that of a regular Slingshot using the same ammo", CriticalStrikeChance = ".02", Location = "Unobtainable" },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba51"), Image = "/images/" + HttpUtility.UrlEncode("Slingshot.png"), Name = "Slingshot", Type = WeaponType.Slingshot.ToString(), Description = "Requires stones for ammo.", Damage = "Depends on ammo used", CriticalStrikeChance = ".02", Location = "The Mines (Floor 40 chest reward)" },
new Weapon() { Id = Guid.Parse("da2fd609-d754-4feb-8acd-c4f9ff13ba52"), Image = "/images/" + HttpUtility.UrlEncode("Master_Slingshot.png"), Name = "Master Slingshot", Type = WeaponType.Slingshot.ToString(), Description = "Requires stones for ammo.", Damage = "Depends on ammo used", CriticalStrikeChance = ".02", Location = "The Mines (Floor 70 chest reward)" }

             );

            base.OnModelCreating(modelBuilder);
        }
    }
}